# Generated by Django 4.1.4 on 2023-01-08 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MathSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('s', 'success'), ('e', 'error'), ('p', 'pending')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('py', 'python'), ('cpp', 'c++'), ('c', 'c')], max_length=10)),
                ('user_input', models.TextField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('s', 'success'), ('e', 'error'), ('p', 'pending')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
